README.md, examples/README.clj, examples/agent.clj, examples/controller.clj, test/puppetlabs/pcp/messaging_test.clj
Update the examples and README to use 8142 as the new production port.  Test
brokers on 8143.
=> (maint) change default port to 8142

test-resources/logback.xml
We'd made the logging too chatty by default for running tests.
Default loglevel is now warn, with info for the broker, and debug
for the code under test.
=> (maint) revisit defaults for test logging

test/puppetlabs/pcp/messaging_test.clj
Until we get a pcp-broker with CTH-351, double the delays on getting reconnected
as it seems that when running on the jenkins hosts the broker is taking longer
to be started than on my MacBook Air.
=> (maint) increase delays for CI

project.clj
Integrate the latest release of pcp-broker to get CTH-351 which should make
testing less painful in CI
=> (maint) update to pcp-broker 0.2.2

examples/agent.clj, examples/controller.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
Here we refactor a little to add a protocol that a pcp client will
implement (ClientInterface) and make Client be implemented as a
record type that implements this protocol.
This allows us to make use of with-open to ensure the close function is called
when we're done with a client, and more cleanly delinates the border between
client API and client implementation.
Also we've reordered some of the functions to match what seemed to be a more
logical narrative for the order of the ClientInterface, and ensured that all
functions are now schematised.
=> PCP-43 enable use of with-open

CHANGELOG.md, CONTRIBUTING.md, Changes.md, README.md
Here we add a CONTRIBUTING.md, a forward reference to our issue tracker to the
README.md, and make the CHANGELOG.md follow the same format as that established
by trapperkeeper-webserver-jetty9 in preparation of being an official
PuppetLabs open library.
=> (maint) prepare to be an open project

src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/messaging_test.clj
When testing our ability to connect to a previously downed broker
we were being too eager in declaring this a failure.  With this
commit we reduce the maximum reconnect delay to 15 seconds, and
then wait twice that time and a little more (40 seconds up from 10)
to see if we did manage to connect to a broker that was previously
down.
This will reduce races in detecting connection success as we saw
in build #14, where we can see the test failure being declared and
interleaved with the successful connection it was looking for:
2015-10-07 06:56:14,704 DEBUG [p.p.client] Making connection to wss://localhost:8143/pcp/
lein test :only puppetlabs.pcp.messaging-test/connect-to-a-down-up-down-up-broker-test
FAIL in (connect-to-a-down-up-down-up-broker-test) (messaging_test.clj:105)
Should now be …
=> (maint) revisit times tested for connection re-attempts

src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
Here we add tracking in for session association in the style of the
existing connection tracking.  This adds `wait-for-assocation`,
`associated?`, and `associate-response-received?` which behave
similarly to `wait-for-connection` and `open?`.
As a side effect of this a user can no longer specify their own
`http://puppetlabs.com/associate_response` handler, as we force our
internal one to be used over a user-supplied one, so we can be sure
that our callback is the one that gets used.
=> PCP-4 Handle session association in the client

examples/agent.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
Here we rework the way we track state, eliminating some duplicate state
tracking that was causing race conditions.
Now we can reliably see if a client is connected by checking the state of the
future in the :websocket-connection atom, and the state of association by
checking the promise in the :associate-response atom.
We remove the additional states of :closing and :closed, rename open? to
connected? and so now just support `connecting?` `connected?` `associating?`
`associated?` to inspect client state.
=> PCP-59 remove :state atom, determine state by inspection

.travis.yml, README.md, project.clj, test/puppetlabs/pcp/messaging_test.clj
Here we change our project to deploy to clojars, consume public components, and add travis to help us verify.
=> PCP-47 deploy to clojars

src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj
In this commit we add the option to include a ```:user-data``` field in the ```puppetlabs.pcp.client/Client``` defrecord. The filed is not used by the ```clj-pcp-client``` at all, it is meant to be used by the users of the client.
=> PCP-346 Add a user-data field to the clj-pcp-client

src/puppetlabs/pcp/client.clj
Improving the docstrings of the Client interface. Making it clear that
unhandled exceptions that were thrown during a WebSocket connection
attempt will propagate through connection state inspectors.
=> (maint) Improve interface documentation

README.md, src/puppetlabs/pcp/client.clj
Adding the start-heartbeat-task to the Client interface; it will be up
to the client code to actually start the heartbeat task to keep the
WebSocket connection up.
Removing the call that starts the heartbeat task right before spawning
the make-connection thread (in the 'connect' function).
=> (PCP-357) Don't start heartbeat task before connecting

dev-resources/Makefile.i18n, locales/messages.pot, project.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
This commit removes the `^:always-validate` attribute from all functions in this projects which used it in order to disable the schema validation for those functions by default.
To compensate for that the tests in this project now use the `schema.test/validate-schemas` fixture so that they still run with the validations enabled.
=> (PCP-488) Disable schema validations by default

test/puppetlabs/pcp/client_test.clj
The state of a dummy PCP client used by some tests in this project was racy as it contained a `(future )` field which may have or may have not been realized at the time the tests were testing it, which was causing occasional test failures.
This commit makes sure the state of the dummy PCP client is stable (i.e. its `(future )` field is realized) before its handed over to the tests.
=> (maint) Fix race condition in tests

locales/messages.pot, project.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/messaging_test.clj
In PCP version 1,  responses (such as `inventory_response`) can exceed
the default max message size in WebSockets (64KB). Make the max message
size configurable, so clients can determine how large a message they'd
like to handle.
=> (PCP-480) Make max binary message size configurable

locales/messages.pot, project.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/messaging_test.clj
Asserts that testing receives a websocket message that's larger than the
configured limit.
=> (maint) Assert websocket too large message is logged

locales/messages.pot, project.clj, src/puppetlabs/pcp/client.clj, test-resources/logback.xml, test/puppetlabs/pcp/messaging_test.clj
Avoid flooding the broker with connections during startup/shutdown when pcp-client is active. This seems to make tests with broker startup/shutdown more reliable.
Also bump to pcp-broker 0.7.1, extract service config to a variable, and reduce logging during testing.
=> (PCP-518) Add delay between each reconnect attempt after close

src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
Restores reporting disconnected immediately after the connection is
closed. Previously - after PCP-518 - the connection would report
connected while waiting to try re-establishing the connection.
Schema checks may be incorrectly used to verify API behavior. Ensure we
run some testing without all schemas enabled to verify correct behavior.
=> (PCP-537, PCP-535) Report disconnected immediately on connection close, don't enable schema during testing

locales/messages.pot, project.clj, src/puppetlabs/pcp/client.clj, test-resources/logback-test.xml, test/puppetlabs/pcp/messaging_test.clj
Catches exceptions that occur while trying to establish a connection or
operate on a connection. Connections can be unexpectedly closed at any
time, and our public APIs should handle failures appropriately.
Specifically we move to catching execution exceptions when dereferencing
the websocket-connection. It seems like we have a few cases:
- `connected?` and `wait-for-connection` catch the exceptions and return
appropriately (`connected?` returns false if an exception occured, and
`wait-for-connection` returns nil signifying no connection was
established)
- `send!` throws a not-connected exception wrapping the original failure
- `close` catches and swallows (logs) failure, as it's not supposed to
attempt supposed to attempt to close the websocket-connection if not
connected
Also catch …
=> (PCP-544) Make client operations more reliable

README.md, examples/README.clj, examples/agent.clj, examples/controller.clj, locales/messages.pot, project.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
Adapt clj-pcp-client to support PCP v2 and drop support for PCP v1.
* drop usage of session association
* drop usage of message expiration
* switch to using v2 functions from pcp-commons
* update examples
=> (PCP-652) adapt client to support PCP v2

src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/messaging_test.clj
When calling wait-for-connection after on-close has been called,
dereferencing the websocket-connection atom can return the future to a
sleep call. Waiting on that future will always wait the sleep period
and return nil. Change to using a single future for checking whether to
stop or retry connecting.
=> (maint) Fix race in wait-for-connection

CHANGELOG.md, README.md, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
- Manage heartbeat thread automatically
- Remove identity
- Allow passing SSLContext instead of cert names
=> (PCP-700) Support usage in pcp-broker

CHANGELOG.md, README.md, project.clj, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/messaging_test.clj
Adds a new on-close callback option to pass in a callback that's called
when the websocket connection closes. Sync all operation is async, this
allows action to be taken whenever the connection is lost.
=> (PCP-713) Add an on-close callback, called when the client disconnects

src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/messaging_test.clj
Add an optional on-connect callback to allow clients to execute a
function when they disconnect from a server.
=> (PCP-701) add on-connect callback function

.travis.yml, CHANGELOG.md, project.clj, test/puppetlabs/pcp/messaging_test.clj
Depends on https://github.com/puppetlabs/clj-pcp-common/pull/41.
=> (maint) Prep 1.2.0 with support for Java 9, Clojure 1.9

.travis.yml, CHANGELOG.md, project.clj
This updates clj-parent to 3.1.1, pcp-common to 1.3.0 (to remove
a warning about uuid? name collision), and updates the changelog
for a release.
=> (maint) update clj-parent, pcp-common and changelog for release

test/puppetlabs/pcp/messaging_test.clj
This commit updates the TLS Handshake regex to account for a possible
race condition. It seems possible for the "Sleeping for up to 200 ms"
message can occur without being logged at warn level (from a regular
connection failure), so the first message in the logs has the 400 ms
timeout instead. This commit should help avoid that issue.
=> (maint) Update messaging_test regex

project.clj
This commit updates clj-parent to 4.6.20 to update Jetty
to 9.4.40. This resolves a number of CVEs and issues in Jetty.
Also update pcp-broker (1.6.2) pcp-common (1.3.4)
and stylefruits/gniazdo (1.2.0).
=> (PE-31800) update clj-parent to 4.6.20

project.clj
This commit removes all references to the pl-clojure-style repo. This was used
for linting / style checking in the past, but hasn't been used for quite some
time, so no reason to keep the `cljfmt` profile for running it.
=> (maint) Remove pl-clojure-style linter

CHANGELOG.md, project.clj
This updates the clj-parent version to 5.2.9, which contains a version declaration for stylefruits/gniazdo, allowing the version in this repository to not pin a specific version.
The release series was bumped up to 1.4.x due to the changes in clj-parent.
The CHANGELOG was also updated in anticipation of a release.
=> (PE-34653) update clj-parent to 5.2.9 remove stylefruits pin

.github/workflows/lein-test.yaml
Accidentally not removed as Jetty 10 can't run under it.
=> (maint) Remove jdk8 testing from gh action

CHANGELOG.md, src/puppetlabs/pcp/client.clj, test/puppetlabs/pcp/client_test.clj, test/puppetlabs/pcp/messaging_test.clj
Recently the additional `certs` entry was needed in the `Client` record, but wasn't added to the record definition.  If schema validation is turned on, this causes an exception to be thrown.
This updates the record to contain the certs entry, adds the schema validation to both test namespaces, and removes an unused parameter.
A pointless test was removed as it violated the schema result of the function, and creating a valid payload would be more effort than the test is worth.
=> (maint) add certs to Client record
